<MyLayout>
    do_default_tab: False

    TabbedPanelItem:
        text: "Tab 1"

        Label:
            text: "Hello world from tab1"

    TabbedPanelItem:
        text: "Tab 2"
        BoxLayout:
            Label:
                text: "Press the Button =>"
            Button:
                text: "Click me!"

    TabbedPanelItem:
        text: "Tab 3"

        Image:
            source: "./images/apple.jpg"

    
        